# Site settings
title:LXC's site
name:Less Or More
email:abc401011721@gmail.com
author:L_XC
url:http://www.samgggg.tk

github:https://github.com/samggggflynn/
baseurl: ""
description: LXC's blog
meta_description: L XC;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: samggggflynn

# Build settings
markdown: kramdown

baidu_analysis: befa8abe1baaeea8c02eb51d5374b659

