# Site settings
name: Xc's Site
email: abc401011721@gmail.com
author: Xc L
url: http://www.samgggg.tk
github: https://github.com/samggggflynn/
resume_site: https://github.com/samggggflynn/
baseurl: ""
description: XC's blog! less is more!
meta_description: XCL;个人博客;学而不思则罔;思而不学则殆
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: samggggflynn
# Build settings
markdown: kramdown

baidu_analysis: befa8abe1baaeea8c02eb51d5374b659

revolvermaps: 5x8ehwr97p6
